### ISSUE TITLE
Update Discover.js when user chooses a past search from my Searches 

### ISSUE THREAD

**Issue by nicolaa5** [NiekBijman/Sentify#17]
The search view should be updated with the data from the past searches when chosen from my Searches. 

My thought is to display the date of the search in **search-date.js** as DD-MM-YYYY / DD-MM-YYYY. Obviously this data will only be available for that specific range, since we can only retrieve data from the last 7 days. 

Loading past search from my Searches into **search.js**:
https://marvelapp.com/867200h/screen/41006916

**Comment by Sahand1993** [comment]
done
