### ISSUE TITLE
Circle Draw: Interactive geocode radius

### ISSUE THREAD

**Issue by nicolaa5** [NiekBijman/Sentify#7]
Steps: 
- Get Long/Lat when clicking on the map 
- Perform a reverse-geocode API call to determine name of clicked location
- Update search-place to show location from the reverse-geocode API
- On mouseDrag animate circle 
- On mouseClick put the Long/Lat endpoint 
- Calculate distance between begin - end point
- Input the geocode + mile as parameter in GET search tweets: 

Example: https://bl.ocks.org/enjalot/0912e1962ed512093895

**Comment by Sahand1993** [comment]
I can do this one
